### ISSUE TITLE
Beta / Test not showing

### ISSUE THREAD

**Issue by AndrewDHokie** [rumstil/eqspellparser#11]
Hey I downloaded the parser.zip. 

I changed winparser.config to:

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
	  <add key="AltServers" value="-test,-beta" />
  </appSettings>
</configuration>

I'm not seeing the test or beta buttons however to download and use that spell data.

![image](https://user-images.githubusercontent.com/1014553/195356677-51143692-3928-4a6c-9e1c-64af1d37090b.png)

Thanks.

**Comment by rumstil** [comment]
Hi there,

Looks like i'm using the wrong filename in the download which I've updated. It should be renamed to **winparser.exe.config**

The file should look like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="AltServers" value="-test,-beta"/>
  </appSettings>
  <startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/></startup>
</configuration>

```

**Comment by AndrewDHokie** [comment]
That did it - THANKS!
